# Working with 3D data

Imagine you have 3d data-sets, e.g.

In [1]:
import numpy as np

data = np.random.randn(4,3)
data_2 = np.eye(3)
data_2 = np.vstack((data_2, [1, 1, 0]))

print(data)
print(data_2)

[[ 0.35558476 -0.51399923 -1.06374603]
 [-1.46875803 -0.60052341 -0.7036728 ]
 [ 0.38638842 -0.51415778 -0.49620269]
 [ 0.70512493  3.73425727 -1.44829376]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]]


## Voluntary Exercise
If you can perform the following tasks, the next exercise will be easy for you:

* Try to find an efficient way to translate these data by [0, 10, 100]
* Try to create a 1-D column vector with the values [0, 10, 100, 1000], and add it to these data
* How can you rotate these data by 10 deg around the y-axis? And what does that mean, e.g. for the vectors [1, 0, 0], and [1, 1, 0]?
* Using one line of code, and scikit-kinematics, can you project the vector [5, 2, 4] into the plane perpendicular to [1, 0, 1]? Can you also draw a diagram for that taks?

### Hints

* Check out https://numpy.org/doc/stable/user/basics.broadcasting.html
* A vector $\vec{x} = \begin{pmatrix}
1\\
2\\
3\\
\end{pmatrix}$ can be rotated by $\vec{x}' = \mathbb{R} * \vec{x}$

In [2]:
import skinematics as skin
Rx = skin.rotmat.R('x', 10)
print(Rx)

[[ 1.          0.          0.        ]
 [ 0.          0.98480775 -0.17364818]
 [ 0.          0.17364818  0.98480775]]


-------------------------------

### Solutions

* Try to create a 1-D column vector with the values [0, 10, 100, 1000], and add it to these data

In [6]:
data_3 = np.array([[0, 10, 100, 1000]]).T

data = np.hstack((data, data_3))
data_2 = np.hstack((data_2, data_3))

print("Dataset 1: \n", data, "\n Dataset 2: \n", data_2)

Dataset 1: 
 [[ 3.55584762e-01 -5.13999233e-01 -1.06374603e+00  0.00000000e+00]
 [-1.46875803e+00 -6.00523412e-01 -7.03672796e-01  1.00000000e+01]
 [ 3.86388423e-01 -5.14157780e-01 -4.96202690e-01  1.00000000e+02]
 [ 7.05124930e-01  3.73425727e+00 -1.44829376e+00  1.00000000e+03]] 
 Dataset 2: 
 [[   1.    0.    0.    0.]
 [   0.    1.    0.   10.]
 [   0.    0.    1.  100.]
 [   1.    1.    0. 1000.]]


* **Try to find an efficient way to translate these data by [0, 10, 100].**

The translation matrix should look like the following:
![Translation matrix](https://i.stack.imgur.com/Vb23q.png)

Where [dx, dy, dz] are going to be the values [0, 10, 100].

In [7]:
Tmatrix =[[1, 0, 0, 0],
          [0, 1, 0, 10],
          [0, 0, 1, 100],
          [0, 0, 0, 1]]


tr_data = Tmatrix * data
tr_data_2 = Tmatrix * data_2
print("First dataset with the translation:\n", tr_data,"\n Second dataset with the translation:\n", tr_data_2)

First dataset with the translation:
 [[ 3.55584762e-01 -0.00000000e+00 -0.00000000e+00  0.00000000e+00]
 [-0.00000000e+00 -6.00523412e-01 -0.00000000e+00  1.00000000e+02]
 [ 0.00000000e+00 -0.00000000e+00 -4.96202690e-01  1.00000000e+04]
 [ 0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.00000000e+03]] 
 Second dataset with the translation:
 [[1.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 1.e+00 0.e+00 1.e+02]
 [0.e+00 0.e+00 1.e+00 1.e+04]
 [0.e+00 0.e+00 0.e+00 1.e+03]]


* **How can you rotate these data by 10 deg around the y-axis? And what does that mean, e.g. for the vectors [1, 0, 0], and [1, 1, 0]?**

To rotate these data, we will use rotation matrices, which are defined in Python with the following function from `skinematics`:

rotmat.R(axis='x', angle=90)

In [8]:
Ry = skin.rotmat.R(axis = 'y', angle = 10)
print('Rotation matrix in 10º in y: \n', Ry)

vector1 = [1,0,0]
vector2 = [1,1,0]

vector1_rot = vector1 * Ry
vector2_rot = vector2 * Ry

print ('Vector 1 rot:\n', vector1_rot, '\nVector 2 rot:\n', vector2_rot)

Rotation matrix in 10º in y: 
 [[ 0.98480775  0.          0.17364818]
 [ 0.          1.          0.        ]
 [-0.17364818  0.          0.98480775]]
Vector 1 rot:
 [[ 0.98480775  0.          0.        ]
 [ 0.          0.          0.        ]
 [-0.17364818  0.          0.        ]] 
Vector 2 rot:
 [[ 0.98480775  0.          0.        ]
 [ 0.          1.          0.        ]
 [-0.17364818  0.          0.        ]]


* **Using one line of code, and scikit-kinematics, can you project the vector [5, 2, 4] into the plane perpendicular to [1, 0, 1]? Can you also draw a diagram for that taks?**

Given a vector ⟨a,b,c⟩ we know that all planes perpendicular to this vector have the form ax+by+cz=d, and any surface of this form is a plane perpendicular to ⟨a,b,c⟩.

In our case, we have the vector [1,0,1], which has the perpendicular plane x+z=d. To express the vector [5,2,4] in this plane, we will have to perform the following operation:

![Projection of a vector](https://i.imgur.com/Doh4hEh.png)

If we look at this geometrically, it would look like the following:

![Projection graphical](https://i.imgur.com/fXXKpYO.png)


In [9]:
vector_a = np.array([5, 2, 4])
vector_b = np.array([1, 0, 1])

projection_a = ((np.dot(vector_a, vector_b))/((np.sqrt(vector_b.dot(vector_b))))*vector_b)
print(projection_a)

[6.36396103 0.         6.36396103]
